sudo: required
dist: dist
language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master